### ISSUE TITLE
Cannot read poperty 'modalName' of undefined

### ISSUE THREAD

**Issue by iKonrad** [anis-campos/redux-reactstrap-modal#2]
Hi, I've installed the plugin but it doesn't seem to work.

I've created a basic modal using the provided example, but when I try to render the component, I get an above error.

I think it's because there's no default state for the modal that I've added and it fails at the line below:
https://github.com/anis-campos/redux-reactstrap-modal/blob/ed2fae2ce9b4bd275df34ecda7878c090871f4a2/src/redux-reactstrap-modal.js#L23

I think there's supposed to be a some sort of default state provided for any new modal, shouldn't it?

**Comment by iKonrad** [comment]
Hey @anis-campos mind checking this PR and merging? It's the only thing preventing me from using the library.

Thanks!

**Comment by anis-campos** [comment]
#3 PR accepted
