### ISSUE TITLE
SSR developing with redux modal - window is not defined 

### ISSUE THREAD

**Issue by YasiruDev** [anis-campos/redux-reactstrap-modal#5]
I'm developing server side rendered react App.I'm using redux modal for sign up.
i'm getting below error.

> /home/xx/Documents/Projects/..../node_modules/redux-reactstrap-modal/build/redux.reactstrap.modal.js:10 })(window, function(WEBPACK_EXTERNAL_MODULE__0, WEBPACK_EXTERNAL_MODULE__1, WEBPACK_EXTERNAL_MODULE__2, WEBPACK_EXTERNAL_MODULE__3, WEBPACK_EXTERNAL_MODULE__4, WEBPACK_EXTERNAL_MODULE__5) { ^
> 
> ReferenceError: window is not defined at Object. (/home/home/xx/Documents/Projects/..../node_modules/redux-reactstrap-modal/build/redux.reactstrap.modal.js:10:4)

[https://stackoverflow.com/questions/54086516/redux-reactstrap-modal-window-is-not-defined-in-ssr](https://stackoverflow.com/questions/54086516/redux-reactstrap-modal-window-is-not-defined-in-ssr)

**Comment by anis-campos** [comment]
Fixed by #8

**Comment by anis-campos** [comment]
Fix is deployed on v2.0.0
