### ISSUE TITLE
Issue with react-redux 6

### ISSUE THREAD

**Issue by slnd94** [anis-campos/redux-reactstrap-modal#6]
I notice when I use with react-redux 6 I get the following error:

> Invariant Violation: Could not find "store" in either the context or props of "Connect(ReduxReactstrapModalContainer)"

Of course it does work when I have react-redux 5.0.7 installed.

Are there any plans to upgrade to react-redux 6?

**Comment by Deimos88** [comment]
Iam getting this error too

**Comment by anis-campos** [comment]
Hi @slnd94 , @Deimos88 

Issue fixed on last release. Let me know if there is still a issue.
